# RETO_S01: 
AZURE_API_KEY: CjRat09L8GVrhOrPmd9N6joXAheENdVCDsXD53S4HBSwvLzaEtuSJQQJ99AJAC5RqLJXJ3w3AAABACOGOG4q
AZURE_ENDPOINT: "https://data-tribe-openai.openai.azure.com/"
AZURE_API_VERSION: "2023-07-01-preview"
MODEL_NAME: "gpt-4"
MODEL_EMBEDDING: "text-embedding-ada-002"
